import { AsciiComponent } from './types';

export const asciiComponents: AsciiComponent[] = [
  // ── Layout ──────────────────────────────────────
  {
    id: 'box',
    name: 'Box / Container',
    category: 'Layout',
    lines: [
      '┌──────────────────┐',
      '│                  │',
      '│                  │',
      '└──────────────────┘',
    ],
    width: 20,
    height: 4,
  },
  {
    id: 'header',
    name: 'Header / Title',
    category: 'Layout',
    lines: [
      '╔══════════════════════════════════════╗',
      '║          Page Title Here             ║',
      '╚══════════════════════════════════════╝',
    ],
    width: 40,
    height: 3,
  },
  {
    id: 'card',
    name: 'Card',
    category: 'Layout',
    lines: [
      '┌──────────────────────┐',
      '│  ┌────────────────┐  │',
      '│  │    Image        │  │',
      '│  └────────────────┘  │',
      '│  Title                │',
      '│  Description text...  │',
      '│  ┌──────────┐        │',
      '│  │  Action  │        │',
      '│  └──────────┘        │',
      '└──────────────────────┘',
    ],
    width: 24,
    height: 10,
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    category: 'Layout',
    lines: [
      '┌────────────┐',
      '│  Menu      │',
      '│ ─────────  │',
      '│  Item 1    │',
      '│  Item 2    │',
      '│  Item 3    │',
      '│  Item 4    │',
      '│            │',
      '└────────────┘',
    ],
    width: 14,
    height: 9,
  },
  {
    id: 'divider',
    name: 'Divider',
    category: 'Layout',
    lines: ['────────────────────'],
    width: 20,
    height: 1,
  },
  {
    id: 'modal',
    name: 'Modal / Dialog',
    category: 'Layout',
    lines: [
      '┌─────────────────────────┐',
      '│  Dialog Title        [x]│',
      '│─────────────────────────│',
      '│                         │',
      '│  Content here...        │',
      '│                         │',
      '│      [Cancel] [  OK  ]  │',
      '└─────────────────────────┘',
    ],
    width: 27,
    height: 8,
  },

  // ── Form ────────────────────────────────────────
  {
    id: 'button',
    name: 'Button',
    category: 'Form',
    lines: [
      '┌──────────┐',
      '│  Button  │',
      '└──────────┘',
    ],
    width: 12,
    height: 3,
  },
  {
    id: 'text-input',
    name: 'Text Input',
    category: 'Form',
    lines: ['Label: [______________]'],
    width: 23,
    height: 1,
  },
  {
    id: 'textarea',
    name: 'Text Area',
    category: 'Form',
    lines: [
      '┌──────────────────┐',
      '│                  │',
      '│                  │',
      '│                  │',
      '└──────────────────┘',
    ],
    width: 20,
    height: 5,
  },
  {
    id: 'checkbox-checked',
    name: 'Checkbox (checked)',
    category: 'Form',
    lines: ['[x] Option selected'],
    width: 19,
    height: 1,
  },
  {
    id: 'checkbox-unchecked',
    name: 'Checkbox (unchecked)',
    category: 'Form',
    lines: ['[ ] Option unselected'],
    width: 20,
    height: 1,
  },
  {
    id: 'radio-selected',
    name: 'Radio (selected)',
    category: 'Form',
    lines: ['(●) Selected option'],
    width: 19,
    height: 1,
  },
  {
    id: 'radio-unselected',
    name: 'Radio (unselected)',
    category: 'Form',
    lines: ['( ) Unselected option'],
    width: 21,
    height: 1,
  },
  {
    id: 'dropdown',
    name: 'Dropdown / Select',
    category: 'Form',
    lines: [
      '┌──────────────┐',
      '│ Select...  ▼ │',
      '└──────────────┘',
    ],
    width: 16,
    height: 3,
  },
  {
    id: 'toggle-off',
    name: 'Toggle (Off)',
    category: 'Form',
    lines: ['[====○    ] Off'],
    width: 15,
    height: 1,
  },
  {
    id: 'toggle-on',
    name: 'Toggle (On)',
    category: 'Form',
    lines: ['[    ●====] On'],
    width: 14,
    height: 1,
  },

  // ── Navigation ──────────────────────────────────
  {
    id: 'navbar',
    name: 'Navigation Bar',
    category: 'Navigation',
    lines: [
      '┌──────────────────────────────────────────────────────┐',
      '│  Logo   │  Home  │  About  │  Blog  │     [Search]   │',
      '└──────────────────────────────────────────────────────┘',
    ],
    width: 56,
    height: 3,
  },
  {
    id: 'tabs',
    name: 'Tabs',
    category: 'Navigation',
    lines: [
      '┌──────┐──────┬──────┐',
      '│ Tab1 │ Tab2 │ Tab3 │',
      '└──────┘      └──────┘',
    ],
    width: 22,
    height: 3,
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    category: 'Navigation',
    lines: ['Home > Products > Category > Item'],
    width: 33,
    height: 1,
  },

  // ── Data ────────────────────────────────────────
  {
    id: 'table',
    name: 'Table',
    category: 'Data',
    lines: [
      '┌──────┬──────┬──────┐',
      '│ Col1 │ Col2 │ Col3 │',
      '├──────┼──────┼──────┤',
      '│      │      │      │',
      '│      │      │      │',
      '└──────┴──────┴──────┘',
    ],
    width: 22,
    height: 6,
  },
  {
    id: 'list',
    name: 'List',
    category: 'Data',
    lines: [
      '• Item one',
      '• Item two',
      '• Item three',
    ],
    width: 12,
    height: 3,
  },
  {
    id: 'avatar',
    name: 'Avatar / Icon',
    category: 'Data',
    lines: [
      '┌───┐',
      '│ A │',
      '└───┘',
    ],
    width: 5,
    height: 3,
  },

  // ── Feedback ────────────────────────────────────
  {
    id: 'progress',
    name: 'Progress Bar',
    category: 'Feedback',
    lines: ['[████████░░░░░░░░] 50%'],
    width: 22,
    height: 1,
  },
];

export const categoryOrder: readonly string[] = [
  'Layout',
  'Form',
  'Navigation',
  'Data',
  'Feedback',
] as const;
